name: time-app
base: core24
version: '0.1'
summary: basic webapp for testing Rack app deployments
description: |
  This is time-app's description.

grade: devel
confinement: devmode

parts:
  time-app:
    plugin: nil
    source: ..
    override-build: |
      ruby -v
      gem install bundler
      bundle install --deployment
      snapcraftctl build

apps:
  time-app:
    command: bundle exec rackup config.ru -o 0.0.0.0 -p $SNAP_MY_RACK_APP_PORT
    daemon: simple
    environment:
      SNAP_TIME_APP_PORT: 80
      PATH: /snap/bin:$PATH
    plugs:
      - network
      - network-bind

